%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [ligth_visor] = visor_transit_fnc_fixpt(visor_coord, visor_slot, ligth_1, bool_v_s)
%visor_transit_fnc - возвращает структуру прошедших через щиток лучей
fm = get_fimath();
ligth = fi(ligth_1, 1, 14, 7, fm);

Y_coord = fi(ligth(:,1) .* visor_coord + ligth(:,2), 1, 14, 7, fm);
if bool_v_s
    ligth(visor_slot < abs(Y_coord)) = fi(NaN, 1, 14, 7, fm);
else 
    %F2F: No information found for converting the following block of code
    %F2F: Start block
    ligth(visor_slot > abs(Y_coord)) = fi(NaN, 1, 14, 7, fm);
    %F2F: End block
end
ligth_visor = fi(ligth(isnan(ligth(:, 1)), :), 1, 14, 7, fm);
end


function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
