%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function ligth_visor = visor_transit_fnc_wrapper_fixpt(visor_coord,visor_slot,ligth,bool_v_s)
    fm = get_fimath();
    visor_coord_in = fi( visor_coord, 0, 2, 0, fm );
    visor_slot_in = fi( visor_slot, 0, 2, 0, fm );
    ligth_in = fi( ligth, 1, 14, 7, fm );
    bool_v_s_in = bool_v_s;
    [ligth_visor_out] = visor_transit_fnc_fixpt( visor_coord_in, visor_slot_in, ligth_in, bool_v_s_in );
    ligth_visor = double( ligth_visor_out );
end

function fm = get_fimath()
	fm = fimath('RoundingMethod', 'Floor',...
	     'OverflowAction', 'Wrap',...
	     'ProductMode','FullPrecision',...
	     'MaxProductWordLength', 128,...
	     'SumMode','FullPrecision',...
	     'MaxSumWordLength', 128);
end
